### ISSUE TITLE
Streamtape, doodstream, streamsb none works

### ISSUE THREAD

**Issue by amanmamta** [Inside4ndroid/resolver#2]
Please try to fix the sources as the videos are not working at all

**Comment by karlioner354** [comment]
streamtape si funciona prueba con este formato de enlace https://streamtape.com/v/lgk1Bq63kOuvRz      usando /v/ en ves de /e/

**Comment by Inside4ndroid** [comment]
> 

what url formats/urls are you using?

doodstream works just fine on my side.

Streamsb will be fixed shortly

streamtape only accepts urls with /v/ but i will be adding a fix so it accepts both /e/ and /v/

**Comment by amanmamta** [comment]
@Inside4ndroid https://dood.ws/e/8sbnxmwsy6cg . I tried with both /e/ and /d/ none works

**Comment by Inside4ndroid** [comment]
the link you have provided seems to work perfectly maybe your ISP is blocking the content.. can you  try with a vpn?

![Untitled](https://user-images.githubusercontent.com/65467186/153134952-373fb489-e6ca-4371-a858-f16b97783ac1.png)

**Comment by amanmamta** [comment]
If I open the link it works that means their is no issue with my ISP. and i even tried with vpn but ntng changed.
![doodstream2](https://user-images.githubusercontent.com/39180934/153136072-0990f92a-4436-4714-b57a-f46f2ca71074.jpg)
![doodstream1](https://user-images.githubusercontent.com/39180934/153136066-defa3d95-22b8-4753-8f7d-fcac4524a94d.jpg)

**Comment by Inside4ndroid** [comment]
Mmm interesting 🤔 I will investigate...

**Comment by amanmamta** [comment]
Sure. BTW can you provide the apk here? So I can confirm.

**Comment by Inside4ndroid** [comment]
here is the latest apk...

https://www.mediafire.com/file/d3x9lpkhb68hqvx/jresolver.apk/file

**Comment by amanmamta** [comment]
It works on my emulator. But not on phone. I guess its useragent or header issue.

**Comment by Inside4ndroid** [comment]
yeah i think it is an issue with request headers working on a fix now..

**Comment by amanmamta** [comment]
Sure. BTW is there any other I can contact you?

**Comment by Inside4ndroid** [comment]
you can email me at suppot@i4studios.co.uk

**Comment by amanmamta** [comment]
I have emailed you please check it..

**Comment by Inside4ndroid** [comment]
will check 

all issues are now fixed :P
