### ISSUE TITLE
Ayuda con estos sitios 

### ISSUE THREAD

**Issue by karlioner354** [Inside4ndroid/resolver#3]
hola te comento que buscando encontré esta otra App proyecto que tiene algunos sitios que tu proyecto no tiene yo sigo el proyecto desde xGetter y me gustaría añadiera sitios que tiene este proyecto URL resolver simple https://github.com/lscofield/URL-resolver-android-simple de antemano gracias!!!

**Comment by karlioner354** [comment]
en ese proyecto funciona Dood adjunto imagen 
![Screenshot_20220211-004850_Url Resolver Simple App](https://user-images.githubusercontent.com/57111363/153539175-e322440f-e4d5-4660-80df-3a876fa8e364.jpg)

**Comment by karlioner354** [comment]
Amigo podrias hacer para el servidor upstream  se obtenga este tipo de link de descarga directa esq el metodo que empleas genera un m3u8 y no lo logro reproducir en VLC aparte que se descarga en mp4 tambien adjunto el enlace que me devuelve la web usando el boton descarga desde la pagina  https://upstream.to/d/81e9kiq2l8jo_n 
 
 https://s30.upstreamcdn.co/w47ryo5l6bbnx2nro3u2ucp2ljotny6ohr76p6pa6kt2lsueht5ds32thxpq/H0c1unr4.14d0.8.D0rd3.105.3131@n135.v4r.4.m0n1n.(Lat-HD-720p).Entrepeliculasyseries.nu.mp4

**Comment by Inside4ndroid** [comment]
hey... i will try to add as many as i can from https://github.com/lscofield/URL-resolver-android-simple 

i will close this for now.. 

also if you would like to try adding some resolvers yourself you could fork the repo and issue pull requests with your changes :)
